pagy:
  page_default: 1
  items_default: 10
  items_maxsize_default: 70
  instances:
    - vars
    - overflow
    - params
user:
  max_length:
    name_roma: 30
    name_kata: 50
    email: 255
    address: 255
  regex:
    email: !ruby/regexp '/\A[^@\s]+@sun-asterisk\.com\z/'
token: 
  access_token_expires_at: 24
